/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulaview;

import aulaprocess.ComponentProcess;
import aularesources.Componente;
import aularesources.EstadoComponente;
import aularesources.TipoComponente;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Arrays;

/**
 *
 * @author The Worst One
 */
public class form extends javax.swing.JFrame {

    private int x, y;
    private home principalWindow;
    private horario thirdWindow;
    private Componente componente;
    private EstadoComponente[][] estadoHorario= new EstadoComponente[7][5];
    private String [][] Asignaturas = new String[7][5];
    
    /**
     * Creates new form form
     */
    public form ()
    {
        setUndecorated(true);
        initComponents();
    }
    
    public form(home principalWindow) {
        setUndecorated(true);
        initComponents();
        this.principalWindow = principalWindow;
        this.thirdWindow = new horario(this);
        setId();
        jTextField1.setText("Aula/Lab 00");
        this.componente = new Componente (jTextField1.getText(), id.getText(), 
                (jComboBox1.getSelectedIndex()==0) ? TipoComponente.AULA : TipoComponente.LABORATORIO );
        for(int i=0;i < 7; i++)
            for(int j=0; j<5; j++)
                estadoHorario[i][j]=EstadoComponente.LIBRE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Arrow_Left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 40));

        id.setBackground(new java.awt.Color(16, 16, 16));
        id.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setOpaque(true);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 40, 30));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Aula/Lab 00");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, 30));

        jLabel5.setBackground(new java.awt.Color(16, 16, 16));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Componente: ");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        jLabel6.setBackground(new java.awt.Color(16, 16, 16));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Componente: ");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AULA", "LABORATORIO" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/order-history.png"))); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, 50));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Aula_logo.png"))); // NOI18N
        jLabel1.setText("AULA   ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 45));

        jLabel7.setBackground(new java.awt.Color(16, 16, 16));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Defina su Horario:");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 30));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/ordering.png"))); // NOI18N
        jButton2.setText("Horario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, 40));

        jLabel8.setBackground(new java.awt.Color(16, 16, 16));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id Componente: ");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/top3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y)  ;
    }//GEN-LAST:event_jLabel1MouseDragged

    public void setPosition (int x, int y)
    {
        setLocation(x, y);
    }
    
    public void setId ()
    {
        id.setText(ComponentProcess.getIdComponente(principalWindow.cantTodosComponentes()));
    }
    
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        x = evt.getX  ()  ;
        y = evt.getY ()  ;
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //setVisible(false);
        //jTextField1.setText("Aula/Lab 00");
        //jComboBox1.setSelectedIndex(0);
        //thirdWindow.setDefault();
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        principalWindow.setPosition(this.getX(), this.getY());
        principalWindow.setVisible(true);
        thirdWindow.dispose();
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        setVisible(false);
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        thirdWindow.setPosition(this.getX(), this.getY());
        thirdWindow.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        // UN POSIBLE PROBLEMA PUEDE SER QUE LAS VENTANAS (JFRAME) ESTAN DESACTUALIZADAS
        // DEBES CREAR UN METODO "SETPRINCIPAL(HOME1 PRINCIPAL)" PARA ACTUALIZAR LOS DATOS
        componente.setNombre(jTextField1.getText());
        componente.setTipoComponente((jComboBox1.getSelectedIndex()==0) ? TipoComponente.AULA : TipoComponente.LABORATORIO);
        
        /*setVisible(false);
        jTextField1.setText("Aula/Lab 00");
        jComboBox1.setSelectedIndex(0); */
        componente.setAsignaturas(Asignaturas);
        componente.setEstadoHorario(estadoHorario);
        
        /*
        for (int i=0; i < 7; i++)
        {
            for (int j=0; j<5; j++)
            {
                System.out.println(estadoHorario[i][j].toString()+ " ");
            } System.out.println();
        }*/
        
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        principalWindow.setPosition(this.getX(), this.getY());
        principalWindow.addComponente(componente);
        principalWindow.setVisible(true);
        thirdWindow.dispose();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public Componente getComponente ()
    {
        return this.componente; 
    }
    
    public void setEstadoHorario (EstadoComponente [][] estadoHorario)
    {
        this.estadoHorario = estadoHorario;
    }
    
    public void setAsignaturas (String [][] Asignaturas)
    {
        this.Asignaturas = Asignaturas;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
