/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulaview;

import aulaprocess.ComponentProcess;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;

import aularesources.EstadoComponente;
import aulaprocess.HorarioProcess;
import javax.swing.JButton;

/**
 *
 * @author The Worst One
 */
public class horario extends javax.swing.JFrame {
    
    private int x, y;
    private form secondWindow;
    private EstadoComponente [][] estadoHorario = {{EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},
                         {EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE, EstadoComponente.LIBRE},};
    private String [][] Asignaturas = new String [7][5];
    private JButton [][] botones;
    /**
     * Creates new form horario
     */
    public horario() {
        setUndecorated(true);
        initComponents();
        this.botones = new JButton[][] {{jButton2, jButton8 , jButton15, jButton22, jButton29},
        {jButton1, jButton9,  jButton16, jButton23, jButton30},
        {jButton3, jButton10,  jButton17, jButton24, jButton31},
        {jButton4, jButton11,  jButton18, jButton25, jButton32},
        {jButton7, jButton12,  jButton19, jButton26, jButton33},
        {jButton6, jButton13,  jButton20, jButton27, jButton34},
        {jButton5, jButton14,  jButton21, jButton28, jButton35}};
    }
    
    public horario (form secondWindow)
    {
        setUndecorated(true);
        initComponents();
        this.secondWindow = secondWindow; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton36 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"07-09", null, null, null, null, null},
                {"09-11", null, null, null, null, null},
                {"11-13", null, null, null, null, null},
                {"13-15", null, null, null, null, null},
                {"15-17", null, null, null, null, null},
                {"17-19", null, null, null, null, null},
                {"19-21", null, null, null, null, null}
            },
            new String [] {
                "Horas", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Arrow_Left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Aula_logo.png"))); // NOI18N
        jLabel1.setText("AULA   ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 45));

        jLabel4.setBackground(new java.awt.Color(12, 12, 12));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Martes");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 40, 20));

        jLabel5.setBackground(new java.awt.Color(12, 12, 12));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("09-11");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 40, 20));

        jLabel6.setBackground(new java.awt.Color(12, 12, 12));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lunes");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 40, 20));

        jLabel7.setBackground(new java.awt.Color(12, 12, 12));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jueves");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 20));

        jLabel8.setBackground(new java.awt.Color(12, 12, 12));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Miercoles");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 40, 20));

        jLabel9.setBackground(new java.awt.Color(12, 12, 12));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Viernes");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 40, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, 20));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 20));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 40, 20));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 40, 20));

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton6.setToolTipText("");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 40, 20));

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton7.setToolTipText("");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 40, 20));

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton8.setToolTipText("");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 40, 20));

        jButton9.setBackground(new java.awt.Color(153, 255, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton9.setToolTipText("");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 40, 20));

        jButton10.setBackground(new java.awt.Color(153, 255, 153));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton10.setToolTipText("");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 40, 20));

        jButton11.setBackground(new java.awt.Color(153, 255, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton11.setToolTipText("");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 40, 20));

        jButton12.setBackground(new java.awt.Color(153, 255, 153));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton12.setToolTipText("");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 40, 20));

        jButton13.setBackground(new java.awt.Color(153, 255, 153));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton13.setToolTipText("");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 40, 20));

        jButton14.setBackground(new java.awt.Color(153, 255, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton14.setToolTipText("");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 40, 20));

        jButton15.setBackground(new java.awt.Color(153, 255, 153));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton15.setToolTipText("");
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 40, 20));

        jButton16.setBackground(new java.awt.Color(153, 255, 153));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton16.setToolTipText("");
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 20));

        jButton17.setBackground(new java.awt.Color(153, 255, 153));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton17.setToolTipText("");
        jButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 40, 20));

        jButton18.setBackground(new java.awt.Color(153, 255, 153));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton18.setToolTipText("");
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 40, 20));

        jButton19.setBackground(new java.awt.Color(153, 255, 153));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton19.setToolTipText("");
        jButton19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 40, 20));

        jButton20.setBackground(new java.awt.Color(153, 255, 153));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton20.setToolTipText("");
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 40, 20));

        jButton21.setBackground(new java.awt.Color(153, 255, 153));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton21.setToolTipText("");
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 20));

        jButton22.setBackground(new java.awt.Color(153, 255, 153));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton22.setToolTipText("");
        jButton22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 20));

        jButton23.setBackground(new java.awt.Color(153, 255, 153));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton23.setToolTipText("");
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 40, 20));

        jButton24.setBackground(new java.awt.Color(153, 255, 153));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton24.setToolTipText("");
        jButton24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 20));

        jButton25.setBackground(new java.awt.Color(153, 255, 153));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton25.setToolTipText("");
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, 20));

        jButton26.setBackground(new java.awt.Color(153, 255, 153));
        jButton26.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton26.setToolTipText("");
        jButton26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton26.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 20));

        jButton27.setBackground(new java.awt.Color(153, 255, 153));
        jButton27.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton27.setToolTipText("");
        jButton27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton27.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 40, 20));

        jButton28.setBackground(new java.awt.Color(153, 255, 153));
        jButton28.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton28.setToolTipText("");
        jButton28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton28.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 40, 20));

        jButton29.setBackground(new java.awt.Color(153, 255, 153));
        jButton29.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton29.setToolTipText("");
        jButton29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton29.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 40, 20));

        jButton30.setBackground(new java.awt.Color(153, 255, 153));
        jButton30.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton30.setToolTipText("");
        jButton30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton30.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 40, 20));

        jButton31.setBackground(new java.awt.Color(153, 255, 153));
        jButton31.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton31.setToolTipText("");
        jButton31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 40, 20));

        jButton32.setBackground(new java.awt.Color(153, 255, 153));
        jButton32.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton32.setToolTipText("");
        jButton32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton32.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 40, 20));

        jButton33.setBackground(new java.awt.Color(153, 255, 153));
        jButton33.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton33.setToolTipText("");
        jButton33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton33.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 40, 20));

        jButton34.setBackground(new java.awt.Color(153, 255, 153));
        jButton34.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton34.setToolTipText("");
        jButton34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton34.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 20));

        jButton35.setBackground(new java.awt.Color(153, 255, 153));
        jButton35.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton35.setToolTipText("");
        jButton35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton35.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 40, 20));

        jLabel10.setBackground(new java.awt.Color(12, 12, 12));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("El componente esta ocupado: ");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 20));

        jLabel11.setBackground(new java.awt.Color(12, 12, 12));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("07-09");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        jLabel12.setBackground(new java.awt.Color(12, 12, 12));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("13-15");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 40, 20));

        jLabel13.setBackground(new java.awt.Color(12, 12, 12));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("11-13");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 40, 20));

        jLabel14.setBackground(new java.awt.Color(12, 12, 12));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("15-17");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, 20));

        jLabel15.setBackground(new java.awt.Color(12, 12, 12));
        jLabel15.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("17-19");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, 20));

        jLabel16.setBackground(new java.awt.Color(12, 12, 12));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("19-21");
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 20));

        jButton36.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/ordering.png"))); // NOI18N
        jButton36.setText("Crear");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 120, 50));

        jLabel17.setBackground(new java.awt.Color(12, 12, 12));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Horas");
        jLabel17.setOpaque(true);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, 20));

        jLabel18.setBackground(new java.awt.Color(12, 12, 12));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/1438860874_help-browser.png"))); // NOI18N
        jLabel18.setText("Estado por horas");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 140, 20));

        jLabel19.setBackground(new java.awt.Color(12, 12, 12));
        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("El componente esta libre: ");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 20));

        jLabel20.setBackground(new java.awt.Color(255, 51, 51));
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel20.setOpaque(true);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 40, 10));

        jLabel21.setBackground(new java.awt.Color(153, 255, 153));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 40, 10));

        jLabel3.setBackground(new java.awt.Color(9, 9, 9));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/top3.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y)  ;
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        x = evt.getX  ()  ;
        y = evt.getY ()  ;
    }//GEN-LAST:event_jLabel1MousePressed

    public void setPosition (int x, int y)
    {
        setLocation(x, y);
    }
    
    public void setDefault ()
    {
        HorarioProcess.setDefault(estadoHorario, Asignaturas, botones);
    }
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setVisible(false);
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        secondWindow.setPosition(this.getX(), this.getY());
        secondWindow.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (estadoHorario[0][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(0, 0, true, Asignaturas);
            if (Asignaturas[0][0]!=null)
            {
                estadoHorario[0][0]=EstadoComponente.OCUPADO;
                jButton2.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[0][0] = EstadoComponente.LIBRE;
            jButton2.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(0, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (estadoHorario[1][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(1, 0, true, Asignaturas);
            if (Asignaturas[1][0]!=null)
            {
                estadoHorario[1][0]=EstadoComponente.OCUPADO;
                jButton1.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[1][0] = EstadoComponente.LIBRE;
            jButton1.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(1, 0,false, Asignaturas);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (estadoHorario[2][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(2, 0, true, Asignaturas);
            if (Asignaturas[2][0]!=null)
            {
                estadoHorario[2][0]=EstadoComponente.OCUPADO;
                jButton3.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[2][0] = EstadoComponente.LIBRE;
            jButton3.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(2, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (estadoHorario[3][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(3, 0, true, Asignaturas);
            if (Asignaturas[3][0]!=null)
            {
                estadoHorario[3][0]=EstadoComponente.OCUPADO;
                jButton4.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[3][0] = EstadoComponente.LIBRE;
            jButton4.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(3, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (estadoHorario[4][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(4, 0, true, Asignaturas);
            if (Asignaturas[4][0]!=null)
            {
                estadoHorario[4][0]=EstadoComponente.OCUPADO;
                jButton7.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[4][0] = EstadoComponente.LIBRE;
            jButton7.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(4, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (estadoHorario[5][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(5, 0, true, Asignaturas);
            if (Asignaturas[5][0]!=null)
            {
                estadoHorario[5][0]=EstadoComponente.OCUPADO;
                jButton6.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[5][0] = EstadoComponente.LIBRE;
            jButton6.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(5, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (estadoHorario[6][0]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(6, 0, true, Asignaturas);
            if (Asignaturas[6][0]!=null)
            {
                estadoHorario[6][0]=EstadoComponente.OCUPADO;
                jButton5.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[6][0] = EstadoComponente.LIBRE;
            jButton5.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(6, 0, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (estadoHorario[0][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(0, 1, true, Asignaturas);
            if (Asignaturas[0][1]!=null)
            {
                estadoHorario[0][1]=EstadoComponente.OCUPADO;
                jButton8.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[0][1] = EstadoComponente.LIBRE;
            jButton8.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(0, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (estadoHorario[1][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(1, 1, true, Asignaturas);
            if (Asignaturas[1][1]!=null)
            {
                estadoHorario[1][1]=EstadoComponente.OCUPADO;
                jButton9.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[1][1] = EstadoComponente.LIBRE;
            jButton9.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(1, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (estadoHorario[2][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(2, 1, true, Asignaturas);
            if (Asignaturas[2][1]!=null)
            {
                estadoHorario[2][1]=EstadoComponente.OCUPADO;
                jButton10.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[2][1] = EstadoComponente.LIBRE;
            jButton10.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(2, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (estadoHorario[3][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(3, 1, true, Asignaturas);
            if (Asignaturas[3][1]!=null)
            {
                estadoHorario[3][1]=EstadoComponente.OCUPADO;
                jButton11.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[3][1] = EstadoComponente.LIBRE;
            jButton11.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(3, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (estadoHorario[4][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(4, 1, true, Asignaturas);
            if (Asignaturas[4][1]!=null)
            {
                estadoHorario[4][1]=EstadoComponente.OCUPADO;
                jButton12.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[4][1] = EstadoComponente.LIBRE;
            jButton12.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(4, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (estadoHorario[5][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(5, 1, true, Asignaturas);
            if (Asignaturas[5][1]!=null)
            {
                estadoHorario[5][1]=EstadoComponente.OCUPADO;
                jButton13.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[5][1] = EstadoComponente.LIBRE;
            jButton13.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(5, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (estadoHorario[6][1]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(6, 1, true, Asignaturas);
            if (Asignaturas[6][1]!=null)
            {
                estadoHorario[6][1]=EstadoComponente.OCUPADO;
                jButton14.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[6][1] = EstadoComponente.LIBRE;
            jButton14.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(6, 1, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (estadoHorario[0][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(0, 2, true, Asignaturas);
            if (Asignaturas[0][2]!=null)
            {
                estadoHorario[0][2]=EstadoComponente.OCUPADO;
                jButton15.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[0][2] = EstadoComponente.LIBRE;
            jButton15.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(0, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (estadoHorario[1][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(1, 2, true, Asignaturas);
            if (Asignaturas[1][2]!=null)
            {
                estadoHorario[1][2]=EstadoComponente.OCUPADO;
                jButton16.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[1][2] = EstadoComponente.LIBRE;
            jButton16.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(1, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if (estadoHorario[2][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(2, 2, true, Asignaturas);
            if (Asignaturas[2][2]!=null)
            {
                estadoHorario[2][2]=EstadoComponente.OCUPADO;
                jButton17.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[2][2] = EstadoComponente.LIBRE;
            jButton17.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(2, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (estadoHorario[3][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(3, 2, true, Asignaturas);
            if (Asignaturas[3][2]!=null)
            {
                estadoHorario[3][2]=EstadoComponente.OCUPADO;
                jButton18.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[3][2] = EstadoComponente.LIBRE;
            jButton18.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(3, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (estadoHorario[4][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(4, 2, true, Asignaturas);
            if (Asignaturas[4][2]!=null)
            {
                estadoHorario[4][2]=EstadoComponente.OCUPADO;
                jButton19.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[4][2] = EstadoComponente.LIBRE;
            jButton19.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(4, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if (estadoHorario[5][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(5, 2, true, Asignaturas);
            if (Asignaturas[5][2]!=null)
            {
                estadoHorario[5][2]=EstadoComponente.OCUPADO;
                jButton20.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[5][2] = EstadoComponente.LIBRE;
            jButton20.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(5, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        if (estadoHorario[6][2]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(6, 2, true, Asignaturas);
            if (Asignaturas[6][2]!=null)
            {
                estadoHorario[6][2]=EstadoComponente.OCUPADO;
                jButton21.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[6][2] = EstadoComponente.LIBRE;
            jButton21.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(6, 2, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        if (estadoHorario[0][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(0, 3, true, Asignaturas);
            if (Asignaturas[0][3]!=null)
            {
                estadoHorario[0][3]=EstadoComponente.OCUPADO;
                jButton22.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[0][3] = EstadoComponente.LIBRE;
            jButton22.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(0, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        if (estadoHorario[1][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(1, 3, true, Asignaturas);
            if (Asignaturas[1][3]!=null)
            {
                estadoHorario[1][3]=EstadoComponente.OCUPADO;
                jButton23.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[1][3] = EstadoComponente.LIBRE;
            jButton23.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(1, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        if (estadoHorario[2][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(2, 3, true, Asignaturas);
            if (Asignaturas[2][3]!=null)
            {
                estadoHorario[2][3]=EstadoComponente.OCUPADO;
                jButton24.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[2][3] = EstadoComponente.LIBRE;
            jButton24.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(2, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        if (estadoHorario[3][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(3, 3, true, Asignaturas);
            if (Asignaturas[3][3]!=null)
            {
                estadoHorario[3][3]=EstadoComponente.OCUPADO;
                jButton25.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[3][3] = EstadoComponente.LIBRE;
            jButton25.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(3, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        if (estadoHorario[4][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(4, 3, true, Asignaturas);
            if (Asignaturas[4][3]!=null)
            {
                estadoHorario[4][3]=EstadoComponente.OCUPADO;
                jButton26.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[4][3] = EstadoComponente.LIBRE;
            jButton26.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(4, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        if (estadoHorario[5][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(5, 3, true, Asignaturas);
            if (Asignaturas[5][3]!=null)
            {
                estadoHorario[5][3]=EstadoComponente.OCUPADO;
                jButton27.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[5][3] = EstadoComponente.LIBRE;
            jButton27.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(5, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        if (estadoHorario[6][3]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(6, 3, true, Asignaturas);
            if (Asignaturas[6][3]!=null)
            {
                estadoHorario[6][3]=EstadoComponente.OCUPADO;
                jButton28.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[6][3] = EstadoComponente.LIBRE;
            jButton28.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(6, 3, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        if (estadoHorario[0][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(0, 4, true, Asignaturas);
            if (Asignaturas[0][4]!=null)
            {
                estadoHorario[0][4]=EstadoComponente.OCUPADO;
                jButton29.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[0][4] = EstadoComponente.LIBRE;
            jButton29.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(0, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        if (estadoHorario[1][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(1, 4, true, Asignaturas);
            if (Asignaturas[1][4]!=null)
            {
                estadoHorario[1][4]=EstadoComponente.OCUPADO;
                jButton30.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[1][4] = EstadoComponente.LIBRE;
            jButton30.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(1, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        if (estadoHorario[2][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(2, 4, true, Asignaturas);
            if (Asignaturas[2][4]!=null)
            {
                estadoHorario[2][4]=EstadoComponente.OCUPADO;
                jButton31.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[2][4] = EstadoComponente.LIBRE;
            jButton31.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(2, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        if (estadoHorario[3][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(3, 4, true, Asignaturas);
            if (Asignaturas[3][4]!=null)
            {
                estadoHorario[3][4]=EstadoComponente.OCUPADO;
                jButton32.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[3][4] = EstadoComponente.LIBRE;
            jButton32.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(3, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        if (estadoHorario[4][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(4, 4, true, Asignaturas);
            if (Asignaturas[4][4]!=null)
            {
                estadoHorario[4][4]=EstadoComponente.OCUPADO;
                jButton33.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[4][4] = EstadoComponente.LIBRE;
            jButton33.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(4, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        if (estadoHorario[5][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(5, 4, true, Asignaturas);
            if (Asignaturas[5][4]!=null)
            {
                estadoHorario[5][4]=EstadoComponente.OCUPADO;
                jButton34.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[5][4] = EstadoComponente.LIBRE;
            jButton34.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(5, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        if (estadoHorario[6][4]==EstadoComponente.LIBRE)
        {
            HorarioProcess.addAsignatura(6, 4, true, Asignaturas);
            if (Asignaturas[6][4]!=null)
            {
                estadoHorario[6][4]=EstadoComponente.OCUPADO;
                jButton35.setBackground(new Color(255, 51, 51));
            }
        }
        else
        {
            estadoHorario[6][4] = EstadoComponente.LIBRE;
            jButton35.setBackground(new Color(153, 255, 153));
            HorarioProcess.addAsignatura(6, 4, false, Asignaturas);
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        //(ComponentProcess.createHorario(secondWindow.getComponente(), estadoHorario, Asignaturas);
        // Maybe ^^^^^^^^  deberia invocar metodos setEstadoHorario y setAsignatura en seconWindow
        setVisible(false);
        secondWindow.setAsignaturas(Asignaturas);
        secondWindow.setEstadoHorario(estadoHorario);
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        secondWindow.setPosition(this.getX(), this.getY());
        secondWindow.setVisible(true);
    }//GEN-LAST:event_jButton36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
