/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulaview;

import aulaprocess.ComponentProcess;
import aulaprocess.HorarioProcess;
import java.awt.MouseInfo;
import java.awt.Point;
import aularesources.Componente;
import aularesources.EstadoComponente;
import aularesources.TipoComponente;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author The Worst One
 */
public class infoAula extends javax.swing.JFrame {

    private int x, y;
    private int fila=-1, columna=-1;
    private home principalWindow;
    private libres orderWindow;
    private Componente componente;
    private EstadoComponente[][] estadoHorario= new EstadoComponente[7][5];
    private String [][] Asignaturas= new String[7][5];
    private JButton [][] botones; /*{{jButton2, jButton8 , jButton15, jButton22, jButton29},
        {jButton1, jButton9,  jButton16, jButton23, jButton30},
        {jButton3, jButton10,  jButton17, jButton24, jButton31},
        {jButton4, jButton11,  jButton18, jButton25, jButton32},
        {jButton7, jButton12,  jButton19, jButton26, jButton33},
        {jButton6, jButton13,  jButton20, jButton27, jButton34},
        {jButton5, jButton14,  jButton21, jButton28, jButton35}}; */
    /**
     * Creates new form form
     */
    public infoAula ()
    {
        setUndecorated(true);
        initComponents();        
        
    }
    
    public infoAula(home principalWindow, Componente componente) {
        setUndecorated(true); 
        initComponents();
        this.principalWindow = principalWindow;
        this.componente = componente;
        this.botones = new JButton[][] {{jButton2, jButton8 , jButton15, jButton22, jButton29},
        {jButton1, jButton9,  jButton16, jButton23, jButton30},
        {jButton3, jButton10,  jButton17, jButton24, jButton31},
        {jButton4, jButton11,  jButton18, jButton25, jButton32},
        {jButton7, jButton12,  jButton19, jButton26, jButton33},
        {jButton6, jButton13,  jButton20, jButton27, jButton34},
        {jButton5, jButton14,  jButton21, jButton28, jButton35}};
        Asignaturas = componente.getAsignaturas();
        estadoHorario = componente.getEstadoHorario();
        
        ComponentProcess.setAsignaturas(componente, Asignaturas);
        ComponentProcess.setId(componente, id);
        ComponentProcess.setName(componente, nameComponent);
        ComponentProcess.setTipoComponente(componente, typeComponent);
        ComponentProcess.setEstadoHorario(componente, estadoHorario);
        
        HorarioProcess.initHorario(estadoHorario, botones);
        
        //estadoHorario = new EstadoComponente[7][5];
        //Asignaturas = new String[7][5];
    }
    
    public infoAula(libres orderWindow, Componente componente) {
        setUndecorated(true);
        initComponents();
        this.orderWindow = orderWindow;
        this.componente = componente;
        this.botones = new JButton[][] {{jButton2, jButton8 , jButton15, jButton22, jButton29},
        {jButton1, jButton9,  jButton16, jButton23, jButton30},
        {jButton3, jButton10,  jButton17, jButton24, jButton31},
        {jButton4, jButton11,  jButton18, jButton25, jButton32},
        {jButton7, jButton12,  jButton19, jButton26, jButton33},
        {jButton6, jButton13,  jButton20, jButton27, jButton34},
        {jButton5, jButton14,  jButton21, jButton28, jButton35}};
        Asignaturas = componente.getAsignaturas();
        estadoHorario = componente.getEstadoHorario();
        
        ComponentProcess.setAsignaturas(componente, Asignaturas);
        ComponentProcess.setId(componente, id);
        ComponentProcess.setName(componente, nameComponent);
        ComponentProcess.setTipoComponente(componente, typeComponent);
        ComponentProcess.setEstadoHorario(componente, estadoHorario);
        
        HorarioProcess.initHorario(estadoHorario, botones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameAsignatura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nameComponent = new javax.swing.JTextField();
        typeComponent = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton38 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Arrow_Left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Aula_logo.png"))); // NOI18N
        jLabel1.setText("AULA   ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 45));

        id.setBackground(new java.awt.Color(16, 16, 16));
        id.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setOpaque(true);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, 30));

        jLabel6.setBackground(new java.awt.Color(16, 16, 16));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Componente: ");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        nameAsignatura.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        nameAsignatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nameAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 30));

        jLabel5.setBackground(new java.awt.Color(16, 16, 16));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Componente: ");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRE", "OCUPADO" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        jLabel17.setBackground(new java.awt.Color(12, 12, 12));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Horas");
        jLabel17.setOpaque(true);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, 20));

        jLabel11.setBackground(new java.awt.Color(12, 12, 12));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("07-09");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 40, 20));

        jLabel7.setBackground(new java.awt.Color(12, 12, 12));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("09-11");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 20));

        jLabel13.setBackground(new java.awt.Color(12, 12, 12));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("11-13");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 20));

        jLabel12.setBackground(new java.awt.Color(12, 12, 12));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("13-15");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 40, 20));

        jLabel14.setBackground(new java.awt.Color(12, 12, 12));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("15-17");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 40, 20));

        jLabel15.setBackground(new java.awt.Color(12, 12, 12));
        jLabel15.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("17-19");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 40, 20));

        jLabel16.setBackground(new java.awt.Color(12, 12, 12));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("19-21");
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 40, 20));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 40, 20));

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton6.setToolTipText("");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 40, 20));

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton7.setToolTipText("");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 40, 20));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 40, 20));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 40, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 40, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 40, 20));

        jLabel8.setBackground(new java.awt.Color(12, 12, 12));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lunes");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 40, 20));

        jLabel9.setBackground(new java.awt.Color(12, 12, 12));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Martes");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 40, 20));

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton8.setToolTipText("");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 40, 20));

        jButton9.setBackground(new java.awt.Color(153, 255, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton9.setToolTipText("");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 40, 20));

        jButton10.setBackground(new java.awt.Color(153, 255, 153));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton10.setToolTipText("");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 40, 20));

        jButton11.setBackground(new java.awt.Color(153, 255, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton11.setToolTipText("");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 40, 20));

        jButton12.setBackground(new java.awt.Color(153, 255, 153));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton12.setToolTipText("");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 40, 20));

        jButton14.setBackground(new java.awt.Color(153, 255, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton14.setToolTipText("");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 40, 20));

        jButton13.setBackground(new java.awt.Color(153, 255, 153));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton13.setToolTipText("");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 40, 20));

        jButton21.setBackground(new java.awt.Color(153, 255, 153));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton21.setToolTipText("");
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 40, 20));

        jButton20.setBackground(new java.awt.Color(153, 255, 153));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton20.setToolTipText("");
        jButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 20));

        jButton19.setBackground(new java.awt.Color(153, 255, 153));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton19.setToolTipText("");
        jButton19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 40, 20));

        jButton18.setBackground(new java.awt.Color(153, 255, 153));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton18.setToolTipText("");
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 40, 20));

        jButton17.setBackground(new java.awt.Color(153, 255, 153));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton17.setToolTipText("");
        jButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 40, 20));

        jButton16.setBackground(new java.awt.Color(153, 255, 153));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton16.setToolTipText("");
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 20));

        jButton15.setBackground(new java.awt.Color(153, 255, 153));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton15.setToolTipText("");
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 40, 20));

        jLabel10.setBackground(new java.awt.Color(12, 12, 12));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Miercoles");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 40, 20));

        jLabel18.setBackground(new java.awt.Color(12, 12, 12));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Jueves");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 20));

        jButton22.setBackground(new java.awt.Color(153, 255, 153));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton22.setToolTipText("");
        jButton22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 40, 20));

        jButton23.setBackground(new java.awt.Color(153, 255, 153));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton23.setToolTipText("");
        jButton23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 40, 20));

        jButton24.setBackground(new java.awt.Color(153, 255, 153));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton24.setToolTipText("");
        jButton24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 40, 20));

        jButton25.setBackground(new java.awt.Color(153, 255, 153));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton25.setToolTipText("");
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 40, 20));

        jButton26.setBackground(new java.awt.Color(153, 255, 153));
        jButton26.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton26.setToolTipText("");
        jButton26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton26.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 40, 20));

        jButton27.setBackground(new java.awt.Color(153, 255, 153));
        jButton27.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton27.setToolTipText("");
        jButton27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton27.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 40, 20));

        jButton28.setBackground(new java.awt.Color(153, 255, 153));
        jButton28.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton28.setToolTipText("");
        jButton28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton28.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 40, 20));

        jButton35.setBackground(new java.awt.Color(153, 255, 153));
        jButton35.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton35.setToolTipText("");
        jButton35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton35.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 40, 20));

        jButton34.setBackground(new java.awt.Color(153, 255, 153));
        jButton34.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton34.setToolTipText("");
        jButton34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton34.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 40, 20));

        jButton33.setBackground(new java.awt.Color(153, 255, 153));
        jButton33.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton33.setToolTipText("");
        jButton33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton33.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 40, 20));

        jButton32.setBackground(new java.awt.Color(153, 255, 153));
        jButton32.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton32.setToolTipText("");
        jButton32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton32.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 40, 20));

        jButton31.setBackground(new java.awt.Color(153, 255, 153));
        jButton31.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton31.setToolTipText("");
        jButton31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 40, 20));

        jButton30.setBackground(new java.awt.Color(153, 255, 153));
        jButton30.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton30.setToolTipText("");
        jButton30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton30.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 40, 20));

        jButton29.setBackground(new java.awt.Color(153, 255, 153));
        jButton29.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton29.setToolTipText("");
        jButton29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton29.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 20));

        jLabel19.setBackground(new java.awt.Color(12, 12, 12));
        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Viernes");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 40, 20));

        jLabel20.setBackground(new java.awt.Color(16, 16, 16));
        jLabel20.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre de la Asignatura: ");
        jLabel20.setOpaque(true);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 30));

        jLabel21.setBackground(new java.awt.Color(16, 16, 16));
        jLabel21.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Estado del Componente:  ");
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        nameComponent.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        nameComponent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameComponent.setText("Aula/Lab 00");
        getContentPane().add(nameComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, 30));

        typeComponent.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        typeComponent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AULA", "LABORATORIO" }));
        getContentPane().add(typeComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 10));

        jButton36.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/1438860862_view-refresh.png"))); // NOI18N
        jButton36.setToolTipText("Guardar");
        jButton36.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 40, 30));

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/indicators_miicard_tick.png"))); // NOI18N
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 30, 30));

        jLabel22.setBackground(new java.awt.Color(16, 16, 16));
        jLabel22.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Id Componente: ");
        jLabel22.setOpaque(true);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/1438861594_delete.png"))); // NOI18N
        jButton38.setToolTipText("Eliminar");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 40, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/top3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y)  ;
    }//GEN-LAST:event_jLabel1MouseDragged

    /*public void initComponente (Componente componente)
    {
        this.componente = componente;
        //ComponentProcess.setAsignaturas(componente, Asignaturas);
        //ComponentProcess.setEstadoHorario(componente, estadoHorario);
        Asignaturas = componente.getAsignaturas();
        estadoHorario = componente.getEstadoHorario();
        ComponentProcess.setId(componente, id);
        ComponentProcess.setName(componente, nameComponent);
        ComponentProcess.setTipoComponente(componente, typeComponent);
        
        
        //HorarioProcess.initHorario(estadoHorario, botones);
        
        for (int i=0; i<7;i++)
            for (int j=0; j<5; j++)
            {
                if (estadoHorario[i][j]==EstadoComponente.OCUPADO)
                    botones[i][j].setBackground(new Color(255, 51, 51));
                else
                    botones[i][j].setBackground(new Color(153, 255, 153));
            }
    }*/
    
    public void initComponente ()
    {
        ComponentProcess.setAsignaturas(componente, Asignaturas);
        ComponentProcess.setId(componente, id);
        ComponentProcess.setName(componente, nameComponent);
        ComponentProcess.setTipoComponente(componente, typeComponent);
        ComponentProcess.setEstadoHorario(componente, estadoHorario);
        
        HorarioProcess.initHorario(estadoHorario, botones);
    } 
    
    public void setPosition (int x, int y)
    {
        setLocation(x, y);
    }
    
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        x = evt.getX  ()  ;
        y = evt.getY ()  ;
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //setVisible(false);
        //HorarioProcess.setDefault(estadoHorario, Asignaturas, botones);
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        if (principalWindow!=null)
        {
            principalWindow.setPosition(this.getX(), this.getY());
            principalWindow.setVisible(true);
        }
        else
        {
            orderWindow.setPosition(this.getX(), this.getY());
            orderWindow.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

     
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        fila = 6;
        columna = 0;
        HorarioProcess.showAsignatura(Asignaturas[6][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[6][0], jComboBox1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        fila = 5;
        columna = 0;
        HorarioProcess.showAsignatura(Asignaturas[5][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[5][0], jComboBox1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[4][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[4][0], jComboBox1);
        fila = 4;
        columna = 0;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[3][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[3][0], jComboBox1);
        fila = 3;
        columna = 0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[2][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[2][0], jComboBox1);
        fila = 2;
        columna = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[1][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[1][0], jComboBox1);
        fila = 1;
        columna = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[0][0], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[0][0], jComboBox1);
        fila = 0;
        columna = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[0][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[0][1], jComboBox1);
        fila = 0;
        columna = 1;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[1][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[1][1], jComboBox1);
        fila = 1;
        columna = 1;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        HorarioProcess.showAsignatura(Asignaturas[2][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[2][1], jComboBox1);
        fila = 2;
        columna = 1;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[3][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[3][1], jComboBox1);
        fila = 3;
        columna = 1;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[4][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[4][1], jComboBox1);
        fila = 4;
        columna = 1;
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[6][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[6][1], jComboBox1);
        fila = 6;
        columna = 1;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[5][1], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[5][1], jComboBox1);
        fila = 5;
        columna = 1;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[6][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[6][2], jComboBox1);
        fila = 6;
        columna = 2;
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[5][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[5][2], jComboBox1);
        fila = 5;
        columna = 2;
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[4][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[4][2], jComboBox1);
        fila = 4;
        columna = 2;
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[3][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[3][2], jComboBox1);
        fila = 4;
        columna = 2;
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[2][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[2][2], jComboBox1);
        fila = 2;
        columna = 2;
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[1][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[1][2], jComboBox1);
        fila = 1;
        columna = 2;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 
        HorarioProcess.showAsignatura(Asignaturas[0][2], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[0][2], jComboBox1);
        fila = 0;
        columna = 2;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[0][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[0][3], jComboBox1);
        fila = 0;
        columna = 3;
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[1][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[1][3], jComboBox1);
        fila = 1;
        columna = 3;
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[2][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[2][3], jComboBox1);
        fila = 2;
        columna = 3;
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[3][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[3][3], jComboBox1);
        fila = 3;
        columna = 3;
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[4][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[4][3], jComboBox1);
        fila = 4;
        columna = 3;
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[5][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[5][3], jComboBox1);
        fila = 5;
        columna = 3;
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[6][3], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[6][3], jComboBox1);
        fila = 6;
        columna = 3;
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[6][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[6][4], jComboBox1);
        fila = 6;
        columna = 4;
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[5][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[5][4], jComboBox1);
        fila = 5;
        columna = 4;
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[4][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[4][4], jComboBox1);
        fila = 4;
        columna = 4;
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
 
        HorarioProcess.showAsignatura(Asignaturas[3][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[3][4], jComboBox1);
        fila = 3;
        columna = 4;
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        
        HorarioProcess.showAsignatura(Asignaturas[2][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[2][4], jComboBox1);
        fila = 2;
        columna = 4;
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed

        HorarioProcess.showAsignatura(Asignaturas[1][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[1][4], jComboBox1);
        fila = 1;
        columna = 4;
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        HorarioProcess.showAsignatura(Asignaturas[0][4], nameAsignatura);
        HorarioProcess.showEstado(estadoHorario[0][4], jComboBox1);
        fila = 0;
        columna = 4;
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        HorarioProcess.safeHorario(fila, columna, estadoHorario, Asignaturas, nameAsignatura, jComboBox1, botones[fila][columna]);
        
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        
        componente.setNombre(nameComponent.getText());
        componente.setTipoComponente((typeComponent.getSelectedIndex()==0) ? TipoComponente.AULA : TipoComponente.LABORATORIO);
        componente.setAsignaturas(Asignaturas);
        componente.setEstadoHorario(estadoHorario);
        
        if (principalWindow!=null)
        {
        principalWindow.updateComponente(componente);
        
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        
        principalWindow.setPosition(this.getX(), this.getY());
        principalWindow.setVisible(true);
        }
        else
        {
            orderWindow.updateComponente(componente);
            Point point  = MouseInfo.getPointerInfo().getLocation() ;
        
            orderWindow.setPosition(this.getX(), this.getY());
            orderWindow.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        if (principalWindow!=null)
        {
            principalWindow.deleteComponente(componente);
            Point point  = MouseInfo.getPointerInfo().getLocation() ;
        
            principalWindow.setPosition(this.getX(), this.getY());
            principalWindow.setVisible(true);
        }
        else
        {
            orderWindow.deleteComponente(componente);
            Point point  = MouseInfo.getPointerInfo().getLocation() ;
        
            orderWindow.setPosition(this.getX(), this.getY());
            orderWindow.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jButton38ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameAsignatura;
    private javax.swing.JTextField nameComponent;
    private javax.swing.JComboBox<String> typeComponent;
    // End of variables declaration//GEN-END:variables
}
