/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aulaview;

import aulaprocess.ComponentProcess;
import aularesources.Componente;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/**
 *
 * @author The Worst One
 */
public class libres extends javax.swing.JFrame {
    
    private int x, y;
    private boolean order;
    private home principalWindow;
    private infoAula infoWindow;
    //private Componente componente;
    private DefaultListModel orderList = new DefaultListModel();
    private ArrayList <Componente> orderComponentes;// = new ArrayList<>();
    /**
     * Creates new form libres
     */
    public libres() {
        setUndecorated(true);
        initComponents();
        jList1.setModel(orderList);
    }
    
    public libres (home principalWindow, ArrayList<Componente> orderComponentes, boolean order)
    {
        setUndecorated(true);
        initComponents();
        this.principalWindow = principalWindow;
        this.orderComponentes = orderComponentes;
        this.order = order;
        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)jList1.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int index=0; index<orderComponentes.size(); index++)
            orderList.addElement(orderComponentes.get(index));
        jList1.setModel(orderList);
        if (order)
            OrderT.setText( libreT.getText());
        else
            OrderT.setText(ocupadoT.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Order = new javax.swing.JScrollPane();
        OrderT = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();
        ocupado = new javax.swing.JScrollPane();
        libreT = new javax.swing.JTextArea();
        libre = new javax.swing.JScrollPane();
        ocupadoT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Arrow_Left.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/Aula_logo.png"))); // NOI18N
        jLabel1.setText("AULA   ");
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 45));

        jLabel19.setBackground(new java.awt.Color(12, 12, 12));
        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Día:");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 20));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07-09", "09-11", "11-13", "13-15", "15-17", "17-19", "19-21" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 30));

        jComboBox2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 30));

        jLabel20.setBackground(new java.awt.Color(12, 12, 12));
        jLabel20.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/1438860874_help-browser.png"))); // NOI18N
        jLabel20.setText("Buscar Aula");
        jLabel20.setOpaque(true);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 20));

        jLabel21.setBackground(new java.awt.Color(12, 12, 12));
        jLabel21.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Hora: ");
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 40, 20));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        jList1.setBackground(new java.awt.Color(11, 11, 11));
        jList1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setOpaque(false);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 230));

        Order.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Order.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Order.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        Order.setFocusable(false);
        Order.setOpaque(false);

        OrderT.setEditable(false);
        OrderT.setBackground(new java.awt.Color(16, 16, 16));
        OrderT.setColumns(20);
        OrderT.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        OrderT.setForeground(new java.awt.Color(255, 255, 255));
        OrderT.setRows(5);
        OrderT.setAutoscrolls(false);
        OrderT.setFocusable(false);
        OrderT.setVerifyInputWhenFocusTarget(false);
        Order.setViewportView(OrderT);

        getContentPane().add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulaicons/top3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 410));

        ocupado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ocupado.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ocupado.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ocupado.setFocusable(false);
        ocupado.setOpaque(false);

        libreT.setEditable(false);
        libreT.setBackground(new java.awt.Color(16, 16, 16));
        libreT.setColumns(20);
        libreT.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        libreT.setForeground(new java.awt.Color(255, 255, 255));
        libreT.setRows(5);
        libreT.setText("Para buscar una Aula libre en un horario \ndeterminado, debe seleccionar el día y la\n hora que se muestra más abajo.");
        libreT.setAutoscrolls(false);
        libreT.setFocusable(false);
        libreT.setVerifyInputWhenFocusTarget(false);
        ocupado.setViewportView(libreT);

        getContentPane().add(ocupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 60));

        libre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        libre.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        libre.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        libre.setFocusable(false);
        libre.setOpaque(false);

        ocupadoT.setEditable(false);
        ocupadoT.setBackground(new java.awt.Color(16, 16, 16));
        ocupadoT.setColumns(20);
        ocupadoT.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        ocupadoT.setForeground(new java.awt.Color(255, 255, 255));
        ocupadoT.setRows(5);
        ocupadoT.setText("Para buscar una Aula ocupada en un horario \ndeterminado, debe seleccionar el día y la\n hora que se muestra más abajo.");
        ocupadoT.setAutoscrolls(false);
        ocupadoT.setFocusable(false);
        ocupadoT.setVerifyInputWhenFocusTarget(false);
        libre.setViewportView(ocupadoT);

        getContentPane().add(libre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point point  = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y)  ;
    }//GEN-LAST:event_jLabel1MouseDragged

    public void setPosition (int x, int y)
    {
        setLocation(x, y);
    }
    
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

        x = evt.getX  ()  ;
        y = evt.getY ()  ;
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //setVisible(false);
        //HorarioProcess.setDefault(estadoHorario, Asignaturas, botones);
        Point point  = MouseInfo.getPointerInfo().getLocation() ;

        principalWindow.updateComponentes(orderComponentes);
        
        principalWindow.setPosition(this.getX(), this.getY());
        principalWindow.destroyOrderWindow();
        principalWindow.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
     if (jList1.getModel().getSize()>0)
        {
            if (jList1.getSelectedValue()!=null)
            {
                int index = jList1.getSelectedIndex();
                Componente componente = (Componente) orderList.getElementAt(index);

                this.infoWindow = new infoAula(this, componente);

                setVisible(false);
                Point point  = MouseInfo.getPointerInfo().getLocation() ;
                infoWindow.setPosition(this.getX(), this.getY());
                infoWindow.setVisible(true);
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (order)
            ComponentProcess.orderLibre(jComboBox1.getSelectedIndex(), jComboBox2.getSelectedIndex(), orderComponentes, orderList);
        else
            ComponentProcess.orderOcupado(jComboBox1.getSelectedIndex(), jComboBox2.getSelectedIndex(), orderComponentes, orderList);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if (order)
            ComponentProcess.orderLibre(jComboBox1.getSelectedIndex(), jComboBox2.getSelectedIndex(), orderComponentes, orderList);
        else
            ComponentProcess.orderOcupado(jComboBox1.getSelectedIndex(), jComboBox2.getSelectedIndex(), orderComponentes, orderList);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    public void updateComponente (Componente componente)
    {
        ComponentProcess.updateComponent(orderComponentes, componente);
        orderList.clear();
        for (int index=0; index<orderComponentes.size(); index++)
            orderList.addElement(orderComponentes.get(index));
    }
    
    public void deleteComponente (Componente componente)
    {
        orderComponentes.remove(componente);
        orderList.clear();
        for (int index=0; index<orderComponentes.size(); index++)
            orderList.addElement(orderComponentes.get(index));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane Order;
    private javax.swing.JTextArea OrderT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane libre;
    private javax.swing.JTextArea libreT;
    private javax.swing.JScrollPane ocupado;
    private javax.swing.JTextArea ocupadoT;
    // End of variables declaration//GEN-END:variables
}
